# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85d2c3408a33b28e27e7bdf29a38464f211aca5f87f3f21639b1b8c2559cc4dc5c00264f44a03697cadc56d73ec174146c8c273ac76e2d77dbefa34bace479aa

test:
  secret_key_base: 388a686dcba1660744c1a91f153e8693c3f4ffe5c9b2f40fe953f8012aaa6e83ace3bca930b7bfd06ffbabddb328e499887a42f9b21dc03f0b2e2bacf0d68bab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
